id: P000650
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:57:04.816324
source_metadata:
  id: bdr:W1KG3555
  title: གཟུངས་འབུལ་ལག་ལེན
  author: ''
  volumes:
    14711b58b8534a44979083c4ea674848:
      image_group_id: I1KG3626
      title: ''
      volume_number: 1
      total_pages: 118
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
