id: I1F9113B5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:34:50+00:00'
last_modified: '2022-06-07T12:33:27.192837+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3555
  title: གཟུངས་འབུལ་ལག་ལེན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    2D82:
      image_group_id: I1KG3626
      title: ''
      total_pages: 118
      order: 1
      base_file: 2D82.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
